language: python
python:
  - "3.6"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements/all-sources.txt"

# command to run tests
script:
  - "make"

# whitelist
branches:
  only:
    - master
